PFSign/Controllers/SignInController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PFSign.Data;
using PFSign.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PFSign.Controllers
{
    public class SignInController : Controller
    {
        private readonly SignInDBContext _context;

        public SignInController(SignInDBContext context)
        {
            _context = context;
        }

        /// <summary>
        /// 返回某日的签到信息
        /// </summary>
        /// <param name="date"></param>
        /// <returns></returns>
        public async Task<IActionResult> Index(DateTime? date = null)
        {
            ViewBag.Date = date;
            DateTime _date = date?.Date ?? DateTime.UtcNow.Date;
            return View(await (from s in _context.SignIn
                               where s.Time >= _date
                               && s.Time < _date.AddDays(1)
                               orderby s.Time descending
                               select s)
                               .AsNoTracking()
                               .ToListAsync());
        }

        /// <summary>
        /// 返回某人的签到信息
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(string name)
        {
            if (name == null)
            {
                return NotFound();
            }

            var signInList = await (from s in _context.SignIn
                                    where s.Name == name
                                    orderby s.Time descending
                                    select s)
                                    .AsNoTracking()
                                    .ToListAsync();
            if (signInList.Count() == 0)
            {
                return NotFound();
            }

            return View(signInList);
        }

        #region 创建
        public IActionResult Create()
        {
            Request.Cookies.TryGetValue("name", out string name);
            Request.Cookies.TryGetValue("seat", out string seat);
            int.TryParse(seat, out int seatnum);
            if (!String.IsNullOrWhiteSpace(name))
            {
                SignIn model = new SignIn()
                {
                    Name = name,
                    Seat = seatnum
                };
                return View(model);
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Seat")] SignIn signIn)
        {
            if (ModelState.IsValid)
            {
                signIn.Time = DateTime.UtcNow;
                _context.Add(signIn);
                await _context.SaveChangesAsync();
                CookieOptions cookieOptions = new CookieOptions()
                {
                    HttpOnly = true,
                    Expires = DateTime.Today.AddMonths(1),
                };
                Response.Cookies.Append("name", signIn.Name, cookieOptions);
                Response.Cookies.Append("seat", signIn.Seat.ToString(), cookieOptions);
                return RedirectToAction(nameof(Index));
            }
            return View(signIn);
        }
        #endregion

        //#region 删除
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var signIn = await _context.SignIn
        //        .AsNoTracking()
        //        .SingleOrDefaultAsync(m => m.ID == id);
        //    if (signIn == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(signIn);
        //}

        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var signIn = await _context.SignIn.SingleOrDefaultAsync(m => m.ID == id);
        //    _context.SignIn.Remove(signIn);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}
        //#endregion

        public IActionResult Stats(DateTime? start = null, DateTime? end = null)
        {
            ViewBag.Start = start?.Date;
            ViewBag.End = end?.Date ?? DateTime.UtcNow.Date;
            return View();
        }

        public async Task<object> SignInStats(DateTime? start = null, DateTime? end = null)
        {
            DateTime
                _start = start?.Date ?? DateTime.MinValue,
                _end = end?.Date ?? DateTime.UtcNow.Date;
            return await (from s in _context.SignIn
                          where s.Time >= _start
                          && s.Time <= _end.AddDays(1)
                          group s by s.Name into g
                          select new
                          {
                              Name = g.Key,
                              Num = g.Count()
                          })
                          .AsNoTracking()
                          .ToListAsync();
        }

        public async Task<IActionResult> Summary(DateTime? date = null)
        {
            //若没有指定日期则当天
            DateTime day = date?.Date ?? DateTime.UtcNow.Date;
            //获取本周开始时间,作为上周五时间末尾
            DateTime weekEnd = day.AddDays(-((int.Parse((day.DayOfWeek.ToString("d"))) + 2) % 7));
            //上周开始时间
            DateTime weekStart = weekEnd.AddDays(-7);
            //上上周开始时间，用于对比两周签到情况
            DateTime lastWeekStart = weekEnd.AddDays(-14);

            //上周签到信息
            var signed = await (from s in _context.SignIn
                                where s.Time < weekEnd
                                && s.Time >= weekStart
                                select s)
                                .AsNoTracking()
                                .ToListAsync();
            //本周签到次数
            int thisWeekCount = signed.Count();
            //上周签到次数
            int lastWeekCount = await (from s in _context.SignIn
                                       where s.Time < weekStart
                                       && s.Time >= lastWeekStart
                                       select s)
                                       .AsNoTracking()
                                       .CountAsync();
            //上周每个人签到的次数,并降序
            var people = from s in signed
                         group s by s.Name into g
                         select new
                         {
                             Name = g.Key,
                             Num = g.Count(),
                         } into p
                         orderby p.Num descending
                         select p;

            var timestats = from h in Enumerable.Range(0, 24)
                            let t = from s in signed
                                    group s by s.Time.ToLocalTime().Hour into g
                                    orderby g.Key
                                    select g
                            select new
                            {
                                Hour = h,
                                Num = t.SingleOrDefault(x => x.Key == h)?.Count() ?? 0
                            };
                             

            //上周最大签到数
            int maxCount = people.Count() == 0 ? 0 : people.Max(x => x.Num);

            var model = new SummaryViewModel()
            {
                MaxCount = maxCount,
                MaxSigned = from p in people
                             where p.Num == maxCount
                             select p.Name,
                BadSigned = (from p in people
                             where p.Num < 4
                             select p).ToDictionary(x => x.Name, x => x.Num),
                TimeStats = timestats,
                ThisWeekCount = thisWeekCount,
                LastWeekCount = lastWeekCount,
                StartDate = weekStart,
                EndDate = weekEnd
            };

            return View(model);
        }

        #region 检验API
        public async Task<bool> SeatExists(int seat)
        {
            return !await _context.SignIn.AnyAsync(
                e => e.Seat == seat
                && e.Time >= DateTime.Today
                && e.Time < DateTime.Today.AddDays(1));
        }

        public async Task<bool> PersonExists(string name)
        {
            return !await _context.SignIn.AnyAsync(
                e => e.Name == name
                && e.Time >= DateTime.Today
                && e.Time < DateTime.Today.AddDays(1));
        }
        #endregion
    }
}

PFSign/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 攀峰签到</title>
    <link  type="image/x-icon" rel="shortcut icon" href="~/favicon.ico" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="SignIn" asp-action="Create" class="navbar-brand">攀峰签到</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="SignIn" asp-action="Index">今日详情</a></li>
                    <li><a asp-area="" asp-controller="SignIn" asp-action="Stats">签到统计</a></li>
                    <li><a asp-area="" asp-controller="SignIn" asp-action="Summary">一周报表</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - 攀峰签到</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdn.bootcss.com/jquery/2.2.0/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://cdn.bootcss.com/bootstrap/3.3.6/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>